apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "32.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1
    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
    service:
      type: LoadBalancer
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true